### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zylstra**
I see the Sharing Path setting only in the Sharing (Personal) settings, not the Sharing (Administration) settings.

### CODE REVIEW

**Comment by rookie0** [comment]
Actually, there has, will update later.

image

**Comment by zylstra** [comment]
Here's what I see.  Am I doing something wrong?

Image 2021-04-08

**Comment by rookie0** [comment]
Please check your app version >= 0.4.0, those are nightly versions for now.

**Comment by zylstra** [comment]
Mine is 0.3.0.  Why should I upgrade?

How do I upgrade?  Download the code zip file and place it in my apps/ folder?  Or unzip it first, then place it in my apps folder?  Or ...?

**Pull request closed without merging**
